modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="hollow_knight_decor"
version="1.1.0"
displayName="Hollow Knight Decor"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Andromeda and PhantomEye - General help with differet things   Pylo - Without MCreator i couldn't create this mod  Team Cherry - For creating such a beatiful game as Hollow Knight"
authors="Astro, MCreator"
description="Adds bunch of building stuff from game Hollow Knight"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hollow_knight_decor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.hollow_knight_decor]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration