modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="hollow_knight_decor"
version="0.1.3"
displayName="Hollow Knight Decor"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Astro, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.hollow_knight_decor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration